<div class="hero-unit">
    <h1>
        <?php 
            //echo sprintf($this->translate('Welcome to %s<br>'), 'Training Center');
            //echo sprintf($this->translate('version: %s'),'0.0.1'); 

            echo sprintf($this->translate('Welcome to %s<br>'), $this->applicationName);
            echo sprintf($this->translate('version: %s'), $this->version); 
        ?>

        <a href="/application/index" >Index</a>
        <a href="/debug/index" >Debug</a>

    </h1>
</div>